// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      this.dealerPlay = __bind(this.dealerPlay, this);
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      return this.get('playerHand').on('stand', this.dealerPlay);
    };

    App.prototype.dealerPlay = function() {
      var dealer;
      dealer = this.get('dealerHand');
      if (!dealer.at(0).get('revealed')) {
        dealer.at(0).flip();
      }
      if ((dealer.scores()[1] != null) && dealer.scores()[1] < 17) {
        dealer.hit();
        return this.dealerPlay();
      } else if (dealer.scores()[0] < 17) {
        dealer.hit();
        return this.dealerPlay();
      } else {
        return this.gameEnd();
      }
    };

    App.prototype.gameEnd = function() {
      var dealer, player;
      dealer = this.get('dealerHand');
      player = this.get('playerHand');
      if (dealer.scores()[0] > 21) {
        return console.log('dealer bust you win');
      } else if ((dealer.scores(1) || dealer.scores()[0]) > (player.scores()[1] || player.scores()[0])) {
        return console.log('dealer wins');
      } else if ((dealer.scores(1) || dealer.scores()[0]) < (player.scores()[1] || player.scores()[0])) {
        return console.log('player wins');
      } else {
        return console.log('draw');
      }
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
